## 2020. 02. 23.

### 코틀린 - 코루틴 취소와 타임아웃(4)

#### `finally`로 리소스 정리하기

취소 가능한 지연 함수들은 일반적인 방식으로 처리할 수 있도록 [`CancellationException`][kt-cancellation-exception]을 던진다. 예를 들어 `try {...} finally {...}` 표현식과 코틀린 `use` 함수는 코루틴이 취소되면 마무리(finalization) 동작을 평범하게 실행한다:

```kotlin
val job = launch {
    try {
        repeat(1000) { i ->
            println("job: I'm sleeping $i ...")
            delay(500L)
        }
    } finally {
        println("job: I'm running finally")
    }
}
delay(1300L) // delay a bit
println("main: I'm tired of waiting!")
job.cancelAndJoin() // cancels the job and waits for its completion
println("main: Now I can quit.")
```

[`join`][kt-join]과 [`cancelAndJoin`][kt-cancel-and-join] 둘 다 모든 마무리 동작이 끝날 때 까지 대기하기 때문에 위의 예시는 다음과 같이 출력한다.

```
job: I'm sleeping 0 ...
job: I'm sleeping 1 ...
job: I'm sleeping 2 ...
main: I'm tired of waiting!
job: I'm running finally
main: Now I can quit.
```



[kt-cancellation-exception]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-cancellation-exception/index.html



[kt-join]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-job/join.html
[kt-cancel-and-join]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/cancel-and-join.html