# 2025. 02. 25.

## Reactor 3 Reference Guide

### Reactor Core 기능

#### 오류 처리

##### 1. 오류 처리 연산자

###### 1.5. 예외를 잡아 다시 던지기

"예외를 잡아 `BusinessException`으로 감싼 뒤 다시 던지"는 것은 절차적인 방식으로 다음과 같다:

```java
try {
  return callExternalService(k);
}
catch (Throwable error) {
  throw new BusinessException("oops, SLA exceeded", error);
}
```

"폴백 메서드 예시"에서 `flatMap` 내의 마지막 줄을 힌트로 다음과 같이 같은 동작을 리액티브하게 할 수 있다:

```java
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorResume(original -> Flux.error(
            new BusinessException("oops, SLA exceeded", original))
    );
```

하지만 `onErrorMap`을 사용해 동일한 동작을 더 직관적으로 만들 수 있다:

```java
Flux.just("timeout1")
    .flatMap(k -> callExternalService(k))
    .onErrorMap(original -> new BusinessException("oops, SLA exceeded", original));
```

