# 2025. 03. 01.

## Reactor 3 Reference Guide

### Reactor Core 기능

#### 오류 처리

##### 1. 오류 처리 연산자

###### 1.9. 재시도

오류 처리와 관련된 연산자가 하나 더 있다. `retry`는 이름에서도 알 수 있듯, 오류를 만들어내는 시퀀스를 재시도할 수 있게 한다.

한 가지 알아둬야 할 것은 이것이 업스트림 `Flux` 를 **재구독**하여 동작한다는 점이다. 이는 완전히 다른 시퀀스이며 원래 시퀀스는 여전히 종료된 상태다. 이를 확인하기 위해 앞의 예제를 다시 사용해 `onErrorReturn`을 사용하는 대신 `retry(1)`을 추가해 한 번 재시도한다. 다음과 같다:

```java
Flux.interval(Duration.ofMillis(250))
    .map(input -> {
        if (input < 3) return "tick " + input;
        throw new RuntimeException("boom");
    })
    .retry(1)
    .elapsed() // 1. `elapsed`는 각 값에 이전 값이 방출된 이후부터의 기간(duration)을 연관시킨다.
    .subscribe(System.out::println, System.err::println); // 2. `onError`가 있으면 출력한다.

Thread.sleep(2100); // 3. 4x2 틱을 수신하기에 충분한 시간을 확보한다.
```

출력은 다음과 같다:

```
259,tick 0
249,tick 1
251,tick 2
506,tick 0 // 1. 틱 0에서부터 새 `interval`이 시작된다. 250ms의 추가 시간은 4번째 틱에서 예외를 발생시키고 그 이후 재시도하면서 더해진 것이다.
248,tick 1
253,tick 2
java.lang.RuntimeException: boom
```

위 예시에서 볼 수 있듯, `retry(1)`은 단지 틱을 0부터 다시 시작해 원본 `interval`을 재구독하기만 한다. 두 번째 시도에서는 예외가 여전히 발생하므로 포기하고 오류를 다운스트림으로 전파한다.

"동반"(companion) `Flux`를 사용해 특정 실패를 재시도해야 하는지 알려주는 (`retryWhend`이라 불리는)`retry`의 고급 버전이 있다. 이 동반 `Flux`는 연산자에 의해 만들어지지만 사용자에 의해 꾸며져(decorated)서 재시도 조건을 커스터마이즈한다.

동반 `Flux`는 `Retry` 전략/함수에 전달되는 `Flux<RetrySignal`로, `retryWhen`에 단독 파라미터로 전달된다. 사용자로서 여러분은 이 함수를 정의하고 새 `Publisher<?>`를 반환하게 한다. `Retry` 클래스는 추상 클래스지만 단순한 람다로 동반자를 변환하고자 할 경우를 위해 팩토리 메서드(`Retry.from(Function)`)을 제공한다.

재시도 사이클은 다음과 같다:

1. 매번 (재시도 가능성이 있는)오류가 발생할 때마다 `RetrySignal` 하나가 사용자가 꾸민 동반자 `Flux`로 방출된다. 이곳에 있는 `Flux`는 현재까지 모든 시도에 대한 조감도를 제공한다. `RetrySignal`은 오류뿐만아니라 관련된 메타데이터에 대한 접근도 제공한다.
2. 동반자 `Flux`가 값을 방출하면 재시도가 일어난다.
3. 동반자 `Flux`가 완료되면 오류는 삼켜져 재시도 사이클이 멈추고 결과 시퀀스도 완료된다.
4. 동반자 `Flux`가 오류(`e`)를 방출하면 재시도 사이클은 멈추고 결과 시퀀스는 오류 `e`로 끝난다.

앞의 두 사례 사이의 차이점이 중요하다. 단순히 동반자를 완료하는 것은 실질적으로 오류를 삼키는 것이다. `retryWhen`을 사용해 `retry(3)`을 흉내내는 다음 예시를 보자:

```java
Flux<String> flux = Flux
    .<String>error(new IllegalArgumentException()) // 1. 계속 오류를 만들어내 재시도하게 한다.
    .doOnError(System.out::println) // 2. 재시도 전에 `doOnError`로 모든 실패에 대한 로그를 남긴다.
    .retryWhen(Retry.from(companion -> // 3. `Retry`는 아주 단순한 `Function` 람다를 사용한다.
        companion.take(3))); // 4. 여기서 처음 세 개 오류(`take(3)`)는 재시도 가능한 것으로 본 다음 포기한다.
```

앞의 예제는 사실상 빈 `Flux`로 끝나지만 성공적으로 완료된다. 같은 `Flux`에 대한 `retry(3)`는 가장 마지막 오류로 종료되기 때문에 이 `retryWhen` 예시는 `retry(3)`와 정확히 같지는 않다.

몇가지 추가 트릭을 사용해 동일한 동작을 할 수 있다:

```java
AtomicInteger errorCount = new AtomicInteger();
Flux<String> flux =
		Flux.<String>error(new IllegalArgumentException())
				.doOnError(e -> errorCount.incrementAndGet())
				.retryWhen(Retry.from(companion -> // 1. 구체 클래스를 제공하는 대신 `Function` 람다를 사용해 `Retry`를 커스터마이즈한다.
						companion.map(rs -> { // 2. 동반자는 현재까지의 재시도 횟수와 마지막 실패를 가진 `RetrySignal` 객체를 방출한다.
							if (rs.totalRetries() < 3) return rs.totalRetries(); // 3. 세 번의 재시도를 허용하도록 재시도가 3회 미만이면 값을 반환해 방출한다(여기서는 재시도 횟수를 반환한다).
							else throw Exceptions.propagate(rs.failure()); // 4. 시퀀스를 오류로 끝내기 위해 세 번의 재시도 이후 원본 오류를 던진다.
						})
				));
```

>  [!TIP]
>
> `Retry`에 노출된 빌더를 사용해 더 유창한(fluent) 방식으로 동일하게 작성할 수 있을뿐만아니라 더 미세 조정된 재시도 전략도 가능한다. e.g. `errorFlux.retryWhen(Retry.max(3))`

> [!TIP]
>
> [FAQ][reactor-core-fqa-exp-backoff]에서 볼 수 있듯이 비슷한 코드를 사용해 "지수 백오프 재시도" 패턴을 구현할 수 있다.

코어에서 제공하는 `Retry` 헬퍼 `RetrySpec`과 `RetryBackoffSpec` 둘 다 다음과 같은 더 고급 커스터마이징을 가능하게 한다:

* 재시도를 유발할 수 있는 예외에 대한 `filter(Predicate)` 설정
* `modifyErrorFilter(Function)`을 통해 이전에 설정된 필터 변형
* (`doBeforeRetry()`와 `doAfterRetry()`를 추가해)재시도가 검증된 경우 재시도 유발시(백오프 전과 지연시간 이후) 로그를 남기는 것과 같은 부수 효과를 유발.
* (`doBeforeRetry()`와 `doAfterRetry()`를 추가해) 재시도 유발시 비동기 `Mono<Void>`를 유발해 기본 지연 시간에 비동기 동작을 추가해 트리거를 더 지연.
* `onRetryExhaustedThrow(BiFunction)`으로 최대 시도 횟수에 도달한 경우 예외를 커스터마이징. 기본적으로 `Exceptions.isRetryExhausted(Throwable)`과 구별되는 `Exceptions.retryExhausted(...)`가 사용된다.
* *일시적 오류* 처리 활성화



[reactor-core-fqa-exp-backoff]: https://projectreactor.io/docs/core/release/reference/faq.html#faq.exponentialBackoff