# 2025. 03. 02.

## Reactor 3 Reference Guide

### Reactor Core 기능

#### 오류 처리

##### 1. 오류 처리 연산자

###### 1.9. 재시도

###### 1.9.1. 임시 오류와 함께 재시도

오랜 시간 살아있는(long-lived) 소스는 오랫동안 잘 실행되다가도 때때로 오류가 발생할 수 있다. 이 문서는 이러한 패턴의 오류를 *임시 오류*(transient errors)라 부른다.

이러한 경우에는 발생한 각 오류를 격리해서 처리해 다음 오류 발생이 이전 재시도 상태를 이어받지 않도록 하는 것이 바람직하다. 예를 들어, 각각의 후속 오류에 대한 지수 백오프 전략은 재시도 지연 시간을 계속 증가하는 것보다 최소 백오프 `Duration`으로 하는 것이 좋다.

`retryWhen` 상태를 나타내는 `RetrySignal` 인터페이스는 이를 위해 사용할 수 있는 `totalRetriesInARow()` 값을 갖는다. 단조롭게(monotonically) 증가하는 `totalRetries()` 인덱스 대신, 이 2차 인덱스는 오류가 재시도에 의해 회복될 때(i.e. 재시도가 `onError` 대신 `onNext`로 끝날 경우)마다 0으로 초기화된다.

`RetrySpec`이나 `RetryBackoffSpec`에 `transientErrors(boolean)` 설정 파라미터를 `true`로 설정하면 만들어지는 전략은 `totalRetriesInARow()` 인덱스를 사용해 실질적으로 *임시 오류*를 처리한다. 이 스펙은 인덱스로부터 재시도 패턴을 계산해 스펙의 다른 모든 설정 파라미터가 각 오류 발생에 독립적으로 적용되도록 한다.

```java
AtomicInteger errorCount = new AtomicInteger(); // 1. 설명을 위해 재시도되는 시퀀스에서 오류의 수를 센다.
Flux<Integer> transientFlux = httpRequest.get() // 2. 한 로우(row)에서 두 번 실패한 뒤 회복되는 스트리밍 엔드포인트와 같은 http 소스라고 가정한다.
        .doOnError(e -> errorCount.incrementAndGet()); 

transientFlux.retryWhen(Retry.max(2).transientErrors(true))  // 3. 해당 소스에 대한 `retryWhen`을 사용한다. `transientErrors` 모드에서 최대 2회 재시도한다.
             .blockLast();
assertThat(errorCount).hasValue(6); // 4. 마지막으로 유효한 응답을 받아 `transientFlux`는 `errorCount`에 등록된 `6`회 시도 뒤에 성공적으로 완료해 유효한 응답을 받는다.
```

`transientErrors(true)`가 없으면 설정된 최대 시도 `2`는 두 번째 오류 발생에서 초과해 결과적으로 전체 시퀀스가 실패했을 것이다.

> [!NOTE]
>
> 실제 http 엔드포인트 없이 로컬에서 시도해보려면, `Supplier`로 의사(pseudo) `httpRequest`를 구현할 수 있다:
>
> ```java
> final AtomicInteger transientHelper = new AtomicInteger();
> Supplier<Flux<Integer>> httpRequest = () ->
>     Flux.generate(sink -> { // 1. 오류를 발생시키는 소스를 `generate`한다.
>         int i = transientHelper.getAndIncrement();
>         if (i == 10) { // 2. 카운터가 10에 도달하면 성공적으로 완료한다.
>             sink.next(i);
>             sink.complete();
>         }
>         else if (i % 3 == 0) { // 3. `transientHelper`가 `3`의 배수이면 `onNext`를 방출하고 현재 오류 발생은 끝낸다.
>             sink.next(i);
>         }
>         else {
>             sink.error(new IllegalStateException("Transient error at " + i)); // 4. 다른 경우에는 `onError`를 방출한다. 이는 3회 중 2회이므로 두 번의 `onError` 발생은 한 번의 `onNext`로 인터럽트된다.
>         }
>     });
> ```
>
> 